ROASTS = [
    "You're out of bells again? *Shocking*. Truly.",
    "_Broke?_ That’s what happens when you think generosity pays rent.",
    "All out of coins? I hope that warm feeling inside was worth it.",
    "Zero balance. Just like your *financial instincts*.",
    "Ah, *bankruptcy*. The Nook family business thrives on it. Yes yes.",
    "You gave away your *last coin*? How charitable. How *foolish*.",
    "That was your *final coin*? Good. I was starting to worry you were learning.",
    "Back to square one. *Just how Tom Nook likes it*.",
    "*You’re broke now*. But look on the bright side… oh wait, there isn’t one.",
    "*Congratulations* on your poor life decisions. Literally.",
    "Tom Nook says: Maybe next time, don't gamble your fortune on friendship.",
    "A bold move — giving away your last coin. *Boldly stupid*. Yes! Yes!",
    "You just hit zero. And I’m here to say: _yes yes, I told you so_.",
    "Nothing left? *Perfect*. I was getting bored of you having money.",
    "Out of coins? Time to start _shaking trees_ again, peasant.",
    "Maybe you’ll think twice next time. *But I doubt it*.",
    "That was generous. And by generous, I mean _financially reckless_.",
    "You’ve reached true *Nook™* status: spiritually bankrupt, fiscally destroyed.",
    "A true philanthropist — and a truly broke one.",
    "Coins *gone*. Dignity *questionable*. Progress: *zero*.",
    "Did you just send your last coin? Yes yes, *natural selection in action*.",
    "Hope that transaction was worth it. _You just sponsored someone else’s lifestyle_.",
    "You went all in... and now *you're all out*. Classic move.",
    "Nook Inc. appreciates your consistent _poverty_.",
    "*Zero coins*. _Zero regrets_? Yeah, I doubt that.",
    "You’ve achieved the impossible: being poorer than a _turnip on Sunday_.",
    "Nothing left in the wallet? Sounds like *it’s time for a loan*. Yes yes.",
    "Who needs money when you’ve got… no, wait, you need money.",
    "I’d give you financial advice, but *I profit when you ignore it*.",
    "Just a reminder: _Tom Nook always wins_. Always.",
    "You spent all your savings trying to impress someone. *Plot twist:* _they didn’t even notice_.",

    "Back to zero... again? At this point, you should start paying *me* for entertainment.",
    "Wow. You’ve gone broke more times than I’ve upgraded a tent. Impressive. Pathetic, but impressive.",
    "Ah, bankruptcy #5. Shall I just call it a habit at this point?",
    "You're not just broke — you're *professionally* broke.",
    "You treat money like it's radioactive. The moment you touch it, it's gone.",
    "At this point, I’m convinced you think zero is a personality trait.",
    "You’ve reached a new low. Which is impressive, considering how often you hit rock bottom.",
    "Financial stability clearly isn’t your strong suit. Or even in your wardrobe.",
    "If going broke was an Olympic sport, you'd already have 6 gold medals and an eviction notice.",
    "Even turnips have more market sense than you. And they rot in a week.",
    "Again? You're not poor, you're committed. And I respect that. From a safe, wealthy distance.",
    "You're starting to make the other broke villagers look like Jeff Bezos.",
    "Debt. Zero balance. Repeated failure. You’re really roleplaying this Tom Nook economy, huh?",
    "They say insanity is doing the same thing over and over. You're doing it broke. Yes yes.",
]

BIG_SPENDER_ROASTS = [
    "Wow. Over 50 coins... just to end up broke *and* ignored? Tragic.",
    "You emptied your entire bank account for *what*? Attention? Affection? Grow up.",
    "A bold move. Give everything to someone else and forget to feed yourself. _Classic simp behavior_.",
    "You really dropped 50+ coins like it was confetti. _Hope the silence was worth it_.",
    "You're not generous — you're desperate. _And now, also broke_. Yes yes.",
    "Ah, the age-old tactic: throw money at your problems and hope they flirt back. _Didn't work, did it?_",
    "The Bank of Nook would like to offer you a shovel — _to keep digging that financial grave_.",
    "You’re not donating — you’re investing in delusion.",
    "You sent over 50 coins like a true sugar raccoon. Now you’re just... sugarless.",
    "Congratulations. _You’ve unlocked Simp Level 99_. No coins, no dignity, no regrets? Actually... probably regrets.",
    "From ‘rich with purpose’ to ‘broke and ghosted.’ Powerful arc. _Disney could never_.",
    "At least now you can afford to focus on self-respect. _Since you can’t afford anything else_.",
    "Giving 50+ coins in one go? That’s not charity — that’s a cry for help with sparkles on top.",
    "You're the financial version of a firework. _Big blast, then total darkness_.",
    "Next time, try sending *a message* instead of your entire net worth. Yes yes.",
]
