ROASTS = [
    "You're out of bells again? <b>Shocking</b>. Truly.",
    "Broke? That’s what happens when you think <b>generosity</b> pays rent.",
    "All out of coins? I hope that <b>warm feeling inside</b> was worth it.",
    "Zero balance. Just like your <b>financial instincts</b>.",
    "Ah, <b>bankruptcy</b>. The Nook family business thrives on it. Yes yes.",
    "You gave away your <b>last coin</b>? How <b>charitable</b>. How <b>foolish</b>.",
    "That was your final coin? <b>Good</b>. I was starting to worry you were learning.",
    "Back to <b>square one</b>. Just how Tom Nook likes it.",
    "You’re broke now. But look on the <b>bright side</b>… oh wait, there isn’t one.",
    "Congratulations on your <b>poor life decisions</b>. Literally.",
    "Tom Nook says: Maybe next time, don’t <b>gamble your fortune</b> on friendship.",
    "A bold move — giving away your <b>last coin</b>. Boldly <b>stupid</b>. Yes! Yes!",
    "You just hit <b>zero</b>. And I’m here to say: yes yes, <b>I told you so</b>.",
    "Nothing left? <b>Perfect</b>. I was getting bored of you having money.",
    "Out of coins? Time to start <b>shaking trees</b> again, peasant.",
    "Maybe you’ll <b>think twice</b> next time. But I doubt it.",
    "That was <b>generous</b>. And by generous, I mean <b>financially reckless</b>.",
    "You’ve reached <b>true Nook™ status</b>: spiritually bankrupt, fiscally destroyed.",
    "A true <b>philanthropist</b> — and a truly <b>broke</b> one.",
    "Coins gone. Dignity <b>questionable</b>. Progress: <b>zero</b>.",
    "Did you just send your last coin? Yes yes, <b>natural selection</b> in action.",
    "Hope that transaction was worth it. You just <b>sponsored someone else’s lifestyle</b>.",
    "You went <b>all in</b>... and now you're <b>all out</b>. Classic move.",
    "Nook Inc. <b>appreciates your consistent poverty</b>.",
    "Zero coins. Zero regrets? <b>Yeah, I doubt that</b>.",
    "You’ve achieved the impossible: being <b>poorer than a turnip</b> on Sunday.",
    "Nothing left in the wallet? Sounds like it’s time for a <b>loan</b>. Yes yes.",
    "Who needs money when you’ve got… no, wait, you <b>need money</b>.",
    "I’d give you <b>financial advice</b>, but I <b>profit</b> when you ignore it.",
    "Just a reminder: <b>Tom Nook always wins</b>. Always.",
    "You spent all your savings trying to <b>impress someone</b>. Plot twist: they didn’t even notice.",

    "Back to zero... <b>again</b>? At this point, you should start <b>paying me</b> for entertainment.",
    "Wow. You’ve gone broke more times than I’ve upgraded a <b>tent</b>. <b>Impressive</b>. Pathetic, but impressive.",
    "Ah, <b>bankruptcy #5</b>. Shall I just call it a <b>habit</b> at this point?",
    "You're not just broke — you're <b>professionally broke</b>.",
    "You treat money like it’s <b>radioactive</b>. The moment you touch it, it's gone.",
    "At this point, I’m convinced you think <b>zero is a personality trait</b>.",
    "You’ve reached a <b>new low</b>. Which is impressive, considering how often you hit <b>rock bottom</b>.",
    "Financial stability clearly isn’t your <b>strong suit</b>. Or even in your wardrobe.",
    "If going broke was an <b>Olympic sport</b>, you’d already have 6 gold medals and an <b>eviction notice</b>.",
    "Even <b>turnips</b> have more market sense than you. And they <b>rot in a week</b>.",
    "Again? You’re not poor, you’re <b>committed</b>. And I respect that. From a <b>safe, wealthy distance</b>.",
    "You're starting to make the other broke villagers look like <b>Jeff Bezos</b>.",
    "<b>Debt</b>. <b>Zero balance</b>. <b>Repeated failure</b>. You’re really roleplaying this Tom Nook economy, huh?",
    "They say insanity is doing the same thing over and over. You’re doing it <b>broke</b>. Yes yes.",
]

BIG_SPENDER_ROASTS = [
    "Wow. Over <b>100 coins</b>... just to end up <b>broke and ignored</b>? Tragic.",
    "You emptied your entire bank account for <b>what</b>? <b>Attention?</b> <b>Affection?</b> Grow up.",
    "A bold move. Give everything to someone else and <b>forget to feed yourself</b>. <b>Classic simp behavior</b>.",
    "You really dropped 100+ coins like it was <b>confetti</b>. Hope the <b>silence</b> was worth it.",
    "You’re not <b>generous</b> — you’re <b>desperate</b>. And now, also broke. Yes yes.",
    "Ah, the age-old tactic: throw <b>money at your problems</b> and hope they flirt back. <b>Didn’t work, did it?</b>",
    "The Bank of Nook would like to offer you a <b>shovel</b> — to keep digging that <b>financial grave</b>.",
    "You’re not <b>donating</b> — you’re <b>investing in delusion</b>.",
    "You sent over 100 coins like a true <b>sugar raccoon</b>. Now you’re just... <b>sugarless</b>.",
    "Congratulations. You’ve unlocked <b>Simp Level 99</b>. No coins, no dignity, no regrets? Actually... probably regrets.",
    "From <b>rich with purpose</b> to <b>broke and ghosted</b>. <b>Powerful arc</b>. Disney could never.",
    "At least now you can afford to focus on <b>self-respect</b>. Since you can’t afford anything else.",
    "Giving 100+ coins in one go? That’s not <b>charity</b> — that’s a <b>cry for help</b> with sparkles on top.",
    "You're the <b>financial version of a firework</b>. Big blast, then <b>total darkness</b>.",
    "Next time, try sending <b>a message</b> instead of your <b>entire net worth</b>. Yes yes.",
]
